### PR TITLE
Add a command to list the nginx vhost configurations currently active

### LINKED ISSUE #38: Add links command to see all active sites

### PR DESCRIPTION
**Pull request by Serializator**
I created a draft for this, as I'm not entirely certain whether the output is the most desirable.

Screenshot 2020-12-18 at 00 00 21

What is your opinion @bjarn?

### CODE REVIEW

**Comment by bjarn** [comment]
Sounds great! There's an open issue for that feature (#38). I'll assign it to you 👍

**Comment by Serializator** [comment]
@bjarn, do you want me to make this a proper pull request or do you have any suggestions to improve this?

**Comment by bjarn** [comment]
@Serializator Yes please, this feature has been requested a couple of times now. It was on my to do list so this is great.

Maybe improve it by making it show a table with a list containing the domain and ✅ or ❌ if it is secured or not. Might be helpful :-)

**Comment by Serializator** [comment]
@bjarn, I will do that. As soon as that is done I'll make it a proper pull request! 👍

**Pull request merged**
